controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/Joint State Broadcaster

diff_cont:
    ros__parameters:
      left_wheel_names: ["left_wheel_joint"] 
      right_wheel_names: ["right_wheel_joint"]

      wheel_separation: 0.18 #wheels_per_side: 1
      wheel_radius: 0.0325
      publish_rate: 30.0 
      use stamped_vel: false
#wheel_separation_multiplier: 1.0
# left_wheel_radius_multiplier: 1.0 #right_wheel_radius_multiplier: 1.0
#odom_frame_id: odom
base_frame_id: base_link
# pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# position_feedback: false
# open loop: true
# enable_odom_tf: true
# cmd_vel_timeout: 0.5 #3 seconds # publish_limited_velocity: true
# velocity_rolling_window_size: 10